# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: [
#     'build',
#     '-t', 'gcr.io/bold-gadget-431317-e1/first',
#     '.',
#   ]
#   options:
#     cache_images: false  # Disable image caching